### ISSUE TITLE
Add privacy wrapper for video and applets

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#631]
### TODO 🏁 
- [ ] Implement CF Worker Magic 🧙([tracked here](https://github.com/serlo/serlo.org-cloudflare-worker/issues/66))
- [ ] Add real wording for notice (@inyono ?)
- [ ] Internationalize component (@elbotho)

### How it should work

<details>
<summary>Steps</summary>

- Lazy load the whole thing
- Then get some preview image proxied by the CF Worker
- Display preview Image with play button or other icon for applets
- On Click/Tap/Enter: Load iframe from external service
- Even nicer: get rid of second click to play if possible. (not implemented for wikimedia)
- Use local storage to save decision for this provider?
</details>

### Backlog / TODO later
- Idea: For SEO we could use our lazyload SEO solution and load the iframe directly in the noscript section.
- Geogebra: Get preview image somehow. 
- BR currently not supported and used. might be added later

### Notes
<details>
  <summary>Thumbnail links / autoplay ideas</summary>
  
  **Wikimedia**
[Video link](https://upload.wikimedia.org/wikipedia/commons/1/15/Inerter_vibration_isolation_experiment.webm) -> [Thumbnail link](https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Inerter_vibration_isolation_experiment.webm/1000px--Inerter_vibration_isolation_experiment.webm.jpg)
structure should be: 
`'upload.wikimedia.org/wikipedia/commons' + '/thumb' + '/1/15/{title}' + '/{size}px--{title}.jpg`
with any size.
*Autoplay*: since this is a video element I guess we could directly start it after loading with .play()
`document.getElementById("test").play()`

**YouTube**
```
  const posterUrl = `https://i.ytimg.com/vi/${videoId}/${poster}.jpg`
  const posterUrlFallback = `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`
```
they also have an api that we could use if we register
*Autoplay*: autoplay=1 should work.

**Vimeo**
```https://vimeo.com/api/oembed.json?url=https://vimeo.com/432353``` gives url and size and more nice things. 👍 
*Autoplay*: `https://player.vimeo.com/video/${vimeo[3]}?autoplay=1` should work.

  
</details>

**Comment by Entkenntnis** [comment]
Just stumbled upon a page that is using exactly this method (https://soundofmunichnow.de/):

![grafik](https://user-images.githubusercontent.com/13507950/98341679-856c5600-200f-11eb-9d54-a294bafe495d.png)

Maybe we can take a look at their implementation.

**Comment by elbotho** [comment]
memo, removed youtube image fallback for now to simplify:
```
  React.useEffect(() => {
    const { current } = refVideo

    if (!current) return

    if (!fallback) {
      const img = new Image()
      img.onload = () => {
        if (img.width === 120) {
          //default image width
          setUseFallback(true)
        }
      }
      img.src = posterUrl
    }

    current.style.backgroundImage = `url('${
      fallback ? posterUrlFallback : posterUrl
    }')`

    // Doesn't work correctly when videoId changes
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fallback])
```

**Comment by inyono** [comment]
Nice. I'll look into the CF Worker stuff (or discuss on Monday, if someone else wants to do that).

Regarding cookies: I don't really care. It doesn't negatively affect the UX either way IMHO. So feel free to do what you prefer.

**Comment by elbotho** [comment]
@inyono nice, added it to the local storage to at least hide the warning. looks nicer this way and does not add a lot of code.
In theory we could then also go ahead and add preconnect stuff back in, but I'm not sure if the benefits are noticable.

**Comment by elbotho** [comment]
> IMHO: this is fine to merge after adding appropriate (i18n-)strings (i.e. the children of InfoBar)

@inyono could you provide those? (You're deeper in the topic right now I think, but I can also go ahead and try a draft)
