### ISSUE TITLE
Implement new mockup for user profiles

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#935]
# Todos:

## Frontend
- [x] Add motivation: 
    - [x] Add edit button
    - [x] Add edit button also when user has no motivation text
- [x] Implement profile pic: 
- [x] Edit link: https://community.serlo.org/account/profile
- [x] Add link to chat
- [x] Fix link for not logged in user
- [x] Check whether user has a rocket chat link 
- [x] Add "logined since"
- [x] Add header
- [x] Link Badges to: https://de.serlo.org/community/202923/rollen-der-serlo-community
- [x] Link Roles to: https://de.serlo.org/community/202923/rollen-der-serlo-community

- [x] Add activity diagram
- [x] Add roles
- [x] Add events
- [x] Add last login
- [x] remove comments
- [x] Suggestion from Simon for better profile structuring

## Frontend: Refactoring

- [x] Refactoring CSS
- [x] Fetch motivation + imageUrl + chatUrl from API
- [x] Add semantic HTML elements for header

## Api

- [x] Add `User { imageUrl }`
- [x] Add `User { chatUrl }`
- [x] Add `User { roles }`
- [x] Add `User { events }`
- [x] add `User { motivation }`
- [x] Add statistic data for a user

## Database layer

- [x] Query for user roles
- [x] Query for events
- [x] Query for user activity 

## Infrastructure

- [x] Add changes in module-api
- [x] Add changes in env-staging
- [ ] Add changes in env-production

## Planning needed / Other
- [x] How shall we transition from the old description?
- [x] Analyze: Who has an image in its description / in the community chat? How to retrieve it?
- [x] How shall we retrieve the statistical data?
- [x] Check: Is the element "motivation" well designed?
- [x] How shall roles be displayed?

# Follow Ups:

* Upload of profile picture in Serlo.
* Add diagram for subjects: 
![2021-03-08-183645_812x391_scrot](https://user-images.githubusercontent.com/1327215/110359593-f82d2280-803d-11eb-8c6a-6d7076fea4f2.png)
* Redirect for Rocket.Chat for not logged in user possible?
